name: changes_handler

on:
  # Allows external webhook trigger
  repository_dispatch:
    types: [ generate_migration ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate migration with changes
        run: python -m snowflow.generate_migration --config '${{ toJson(github.event.client_payload.generate_migrations_config) }}'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message:  ${{ github.event.client_payload.commit_name }}
          title: '${{ github.event.client_payload.pull_request_name }}'
          body: ${{ github.event.client_payload.pull_request_message }}
          branch: ${{ github.event.client_payload.branch_name }}
          labels: ${{ github.event.client_payload.labels }}
